# Assessment test 

## Exercise 1: 

What is a correct syntax to output "Hello World" in Python?

1. print("Hello World")
2. echo("Hello World")
3. p("Hello World")
4. printf("Hello World")

**You answer here**  number 1

## Exercise 2:

Which one is NOT a legal variable name?

1. Myvar
2. _myvar
3. my-var
4. my_var 

**Your answer here** number 3

## Exercise 3: range()

Use range() to print all the even numbers from 0 to 10.

In [15]:
# Your code here

for i in range(5):
    print(2*i)

0
2
4
6
8


In [18]:
for i in range(11):
    if i%2==0 :
        print(i)

0
2
4
6
8
10


## Exercise 4: list


```python
>>> arr = ["Car", "Fruit", 1]
```

1. Add element at the top of the list `arr`
2. Add element at the end of the list `arr`
3. remove element "Car" from the list

In [11]:
# Your code here
arr = ["Car", "Fruit", 1]
arr.append("Java")
arr[-4] = 'M'
arr

['M', 'Fruit', 1, 'Java']

In [12]:
arr.insert(0,'Java')

In [13]:
arr

['Java', 'M', 'Fruit', 1, 'Java']

## Exercise 5: slicing

```python
>>> arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
1. Print the first 10 elements
2. Print the last 10 elements 
3. Print the elements between indices 3 and 7
4. Print the elements at odd positions

In [32]:
# Your code here
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
print(arr[0:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
print(arr[-10:])

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [26]:
print(arr[len(arr)-10:])

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [33]:
arr.append(1)

In [34]:
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 1]

In [35]:
print(arr[len(arr)-10:])

[11, 12, 13, 14, 15, 16, 17, 18, 19, 1]


## Exercise 6: List comprehension

Use List comprehension to create a list of all numbers between 1 and 50 that are divisible by 3.

In [36]:
# Your code here
L=[]
for i in range(50):
    if i%3==0 :
        L.append(i)
        
L

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

## Exercise 7: string

Go through the string below and if the length of a word is even print "even!"
```python
>>> st = 'Print every word in this sentence that has an even number of letters'
```

In [43]:
# Your code here
st = 'Print every word in this sentence that has an even number of letters'

In [38]:
len(st)

68

In [39]:
if len(st)%2==0 :
    print('even')

even


In [46]:
s = st.split(" ")
s

['Print',
 'every',
 'word',
 'in',
 'this',
 'sentence',
 'that',
 'has',
 'an',
 'even',
 'number',
 'of',
 'letters']

In [50]:
for i in s :
    if len(i)%2 ==0 :
        print(i, "---------------------->  event")

word ---------------------->  event
in ---------------------->  event
this ---------------------->  event
sentence ---------------------->  event
that ---------------------->  event
an ---------------------->  event
even ---------------------->  event
number ---------------------->  event
of ---------------------->  event


## Exercise 8: string

Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [55]:
# Your code here

for i in range(1,101) :
    if (i%3 == 0) and (i%5 == 0) :
        print("FizzBuzz")
    elif i%5 == 0 :
        print("Buzz")
    elif i%3 == 0 :
         print("Fizz")
    else :
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


## Exercise 9: conditions

1. Compute the odd number squares sum of `arr`

```python
>>> arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

2. Compute the solution of $ax^2 + bx + c = 0$
    - a, b, and c are given by the user

In [62]:
# Your code here
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [70]:
m=0
for i in range(len(arr)) :
    if arr[i]%2 == 1 :
        m += arr[i]**2
        
print(m)


1330


In [86]:
a = int(input())
b = int(input())
c = int(input())

delta = 0
x1=0
x2=0
if a == 0 :
    if b == 0 :
        if c == 0 :
            print(' la solution est l\'ensemble R')
        else : 
            print('pas de solution ')
    else : 
        print(' la solution est :', -c/b)
else :
    delta = pow(b,2) - 4*a*c
    if delta < 0 :
        print('pas de solution dans R')
    
    elif delta == 0 :
        print('la solution est :', -b/(2*a))
      
    else :
        print('les solutions sont : x1 =', (-b + sqrt(delta))/(2*a)," et x2 =", (-b - sqrt(delta))/(2*a))
            

0
0
0
 la solution est l'ensemble R


## Exercise 10: Numpy

1. Define 2 matrices using numpy

![matrix](../data/matrix.png)

2. Compute the multiplication of the 2 matrices

3. Print the result

In [6]:
# Your code here
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
k = [[1,2,3],[4,5,6],[7,8,9]]
B = np.array([[7,8,9],[4,5,6],[1,2,3]])

C = np.dot(A,k)
print(C)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Exercise 11: functions

1. Write function that compute the max of 2 given numbers
2. Call the function with 2 numbers of your choice

In [89]:
# Your code here
def max (a, b) :
    if a > b :
        return a
    else :
        return b

In [93]:
max(10.0012,10.00112)

10.0012

## Exercise 12: Matplotlib
 
1. Write a Python program that will create the plot bellow
![plot](../data/matplotlib.png)

In [1]:
# Your code here
import matplotlib.pyplot as plt 
import numpy as np

x = np.arange(-4,4,0.001)
y = np.sin(x)

plt.plot(x,y)

ModuleNotFoundError: No module named 'matplotlib'

## Exercise 13: pandas

1. Use pandas library to read the csv file 'data.csv' (located at data repository)
2. Print the first 10 rows for the file
3. Print the values of 'diagnosis' column

In [7]:
# Your code here
import pandas as pd
data = pd.read_csv('data.csv' )
print(data[1:1])
print(data.head())

ModuleNotFoundError: No module named 'pandas'

In [2]:
import nu
x = np.array([[1,2,2],[5,6,7]])
x.shape()

NameError: name 'np' is not defined